name: Pipeline

on:
  push:
    branches:
      - developTest

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: npm ci