name: Matrix
on: push
jobs:
  node-version:
    steps:
      - name: Log Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log Node version
        run: node -v