name: Print Env Action

on:
  push:
    paths:
      - "printenv/**"
      - ".github/workflows/printenv.yml"
    branches:
      - develop

jobs:
  get_context:
    name: Get Context
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'printenv')"
    steps:
      - name: print event
        run: |
          echo "${{ toJSON(github.event) }}"
          printenv
